### ISSUE TITLE
Apisix Plugin patch ... I need more info

### ISSUE THREAD

**Issue by egargale** [webbankir/terraform-provider-apisix#1]
Thanks for the Terraform provider for APISIX. 

Could you please add some more information on how patching APISIX.

I understand that I have to:

1. copy the lua files of apisix-lua/plugins to apisix plugin directory
2. provide the apisix's config.yml with the hook and the plugin directory  such as:

```
+  extra_lua_path: "/usr/local/apisix/lua/apisix-lua/?.lua"
+  lua_module_hook: "terraform-hook"

```
3 the hook should load the plugin...

I am not well versed in LUA so I'm sorry to ask but I think that I need to change your hook code to something else
```
  if sub_path == "__patch_terraform_plugin_apisix__" then
      return old_core_table_path(conf, "", conf)
   else
```
as the hook is loaded with no error but the provider is not working. 

Should I change  "_patch_terraform_plugin_apisix_" to the "_extra_lua_path_" ?

Any help is appreciated.

**Comment by suslovsergey** [comment]
@egargale Hi!

it's right config (config.yaml):

```
apisix:
...
  extra_lua_path: /opt/apisix/?.lua
  lua_module_hook: hook
...
```

Now files listing in /opt/apisix:

```
...
/opt/apisix/hook.lua
...
```

And content of hook.lua

```
local apisix = require("apisix")
local core = require("apisix.core")

local old_http_init = apisix.http_init
apisix.http_init = function(...)

    local old_core_table_path = core.table.patch
    core.table.patch = function(node_value, sub_path, conf)
        if sub_path == "__patch_terraform_plugin_apisix__" then
            return old_core_table_path(conf, "", conf)
        else
            return old_core_table_path(node_value, sub_path, conf)
        end
    end

    old_http_init(...)
end
```

**Comment by suslovsergey** [comment]
@egargale  and thanks your for this issue. it's mean that information in readme  is poor. i can fix it in next month only.

**Comment by egargale** [comment]
Many thanks @suslovsergey  It is working now.
